
variables:
    BACKEND_IMAGE_GITLAB: git.cognito.cz:5000/gauss/ga-2502-elasticsearch-plugins

stages:
  - build
  - test
  - build_uber
  - deploy

before_script:
#  - echo `pwd` # debug
  - '[ "$CI_BUILD_TAG" ] && export RELEASE_TAG=$(echo $CI_BUILD_TAG | sed "s/^v//") || RELEASE_TAG=live'
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  image: java:8-jdk
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/distributions/*.zip

unit_test:
  image: java:8-jdk
  stage: test
  script:
    - ./gradlew check



